// Generated by scripts/build_buluo_ref.js from Datasets/buluo/{ami,pwn,pyu}.json — do not hand-edit.
// Re-run the script after Datasets/buluo changes. See Datasets/buluo/DISPLAY.md for how to render these fields.
// BULUO_REF: identity facts for buluo that already have a data.js event entry (joined via buluo_id / buluo_ids).
// BULUO_UNCOVERED: Amis buluo known to the db with NO event entry yet — candidates for the 新增部落 contribution flow.
const BULUO_REF = {
  "ami-palamitan": {
    "chinese_name": "康樂部落",
    "chinese_name_alt": [],
    "indigenous_name": "Palamitan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-katanka": {
    "chinese_name": "佳林部落",
    "chinese_name_alt": [],
    "indigenous_name": "Katanka",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-palinkaan": {
    "chinese_name": "復興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Palinkaan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lalumaang": {
    "chinese_name": "東方羅馬部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lalumaang",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pacidal": {
    "chinese_name": "華陽部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pacidal",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-hupu": {
    "chinese_name": "北埔部落",
    "chinese_name_alt": [],
    "indigenous_name": "Hupu",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kaliyawan": {
    "chinese_name": "嘉里部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kaliyawan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-paudadan": {
    "chinese_name": "大德（巴烏拉藍）部落",
    "chinese_name_alt": [],
    "indigenous_name": "Paudadan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cilapuk": {
    "chinese_name": "嘉新部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilapuk",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pabuisan": {
    "chinese_name": "北星部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pabuisan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pibutingan": {
    "chinese_name": "順安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pibutingan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-patirengan": {
    "chinese_name": "立業部落",
    "chinese_name_alt": [],
    "indigenous_name": "Patirengan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "豐年祭 地圖/data.js (Pokoh)"
    ],
    "notes": "Only attested in data.js (官方 PDF). Absent from the CIP gazette — its data.js festival entry (id hl-xc-14) is itself marked 停辦 (cancelled), consistent with it not currently being a CIP-recognized buluo. Needs an independent source if it's ever revived."
  },
  "ami-sudadatan": {
    "chinese_name": "新城部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sudadatan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kanian": {
    "chinese_name": "嘎尼按部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kanian",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-singsiya": {
    "chinese_name": "新夏部落",
    "chinese_name_alt": [],
    "indigenous_name": "Singsiya",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciku": {
    "chinese_name": "磯固部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciku",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cipawkan": {
    "chinese_name": "德安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cipawkan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cikep": {
    "chinese_name": "幾可普部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cikep",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kenuy": {
    "chinese_name": "根努夷部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kenuy",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lasutan": {
    "chinese_name": "拉署旦部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lasutan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tasutasunan": {
    "chinese_name": "達蘇達蘇湳部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tasutasunan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "sakizaya-sakur": {
    "chinese_name": "撒固兒部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sakur",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-cibarbaran": {
    "chinese_name": "主農部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cibarbaran",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tuwapun": {
    "chinese_name": "華東部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tuwapun",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciripunan": {
    "chinese_name": "慶豐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciripunan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-isaetipan-pahikukian": {
    "chinese_name": "仁和部落",
    "chinese_name_alt": [],
    "indigenous_name": "Isaetipan pahikukian",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cikeliwan": {
    "chinese_name": "歌柳灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cikeliwan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-taracan": {
    "chinese_name": "達拉贊部落",
    "chinese_name_alt": [],
    "indigenous_name": "Taracan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kungkung": {
    "chinese_name": "大鼓部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kungkung",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-citekudan": {
    "chinese_name": "小台東部落",
    "chinese_name_alt": [],
    "indigenous_name": "Citekudan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pukpuk": {
    "chinese_name": "簿簿部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pukpuk",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-atonan": {
    "chinese_name": "阿都南部落",
    "chinese_name_alt": [],
    "indigenous_name": "Atonan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sarad": {
    "chinese_name": "撒樂部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sarad",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciyibangcalay": {
    "chinese_name": "吉野汎扎萊部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciyibangcalay",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-mabuwakay": {
    "chinese_name": "南華部落",
    "chinese_name_alt": [],
    "indigenous_name": "Mabuwakay",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sirakesay": {
    "chinese_name": "永安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sirakesay",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cikasuwan": {
    "chinese_name": "七腳川部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cikasuwan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lidaw": {
    "chinese_name": "里漏部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lidaw",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-hacining": {
    "chinese_name": "干城部落",
    "chinese_name_alt": [],
    "indigenous_name": "Hacining",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-natawran": {
    "chinese_name": "那荳蘭部落",
    "chinese_name_alt": [],
    "indigenous_name": "Natawran",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-buner": {
    "chinese_name": "宜昌部落",
    "chinese_name_alt": [],
    "indigenous_name": "Buner",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-isawalian-pahikukian": {
    "chinese_name": "仁安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Isawalian pahikukian",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fulufuluan": {
    "chinese_name": "勝安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fulufuluan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tdlu": {
    "chinese_name": "豐裡部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tdlu",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cealalupalantdlu": {
    "chinese_name": "豐山部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cealalupalantdlu",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cihak": {
    "chinese_name": "志學部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cihak",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cipuypuyan": {
    "chinese_name": "米棧部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cipuypuyan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-adetuman": {
    "chinese_name": "平和部落",
    "chinese_name_alt": [],
    "indigenous_name": "Adetuman",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-banaw": {
    "chinese_name": "池南部落",
    "chinese_name_alt": [],
    "indigenous_name": "Banaw",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-telu": {
    "chinese_name": "豐坪部落",
    "chinese_name_alt": [],
    "indigenous_name": "Telu?",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tumay": {
    "chinese_name": "鹽寮部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tumay",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciwidiyan": {
    "chinese_name": "水璉部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciwidiyan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-rinahem": {
    "chinese_name": "光榮部落",
    "chinese_name_alt": [],
    "indigenous_name": "Rinahem",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kiku": {
    "chinese_name": "溪口部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kiku",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciamengan": {
    "chinese_name": "壽豐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciamengan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sawanengan": {
    "chinese_name": "共和部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sawanengan",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-taukak": {
    "chinese_name": "樹湖部落",
    "chinese_name_alt": [],
    "indigenous_name": "Taukak",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sariwsiw": {
    "chinese_name": "大榮部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sariwsiw",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cirakayan": {
    "chinese_name": "山興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cirakayan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cingaroan": {
    "chinese_name": "鳳信部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cingaroan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciloohay": {
    "chinese_name": "森榮部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilo'ohay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tangahang": {
    "chinese_name": "長橋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tangahang",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cihafayan": {
    "chinese_name": "中興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cihafayan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-atomo": {
    "chinese_name": "阿陶模部落",
    "chinese_name_alt": [],
    "indigenous_name": "Atomo",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-alolong": {
    "chinese_name": "阿囉隆部落",
    "chinese_name_alt": [],
    "indigenous_name": "Alolong",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sado": {
    "chinese_name": "砂荖部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sado",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lasoay": {
    "chinese_name": "拉索艾部落",
    "chinese_name_alt": [],
    "indigenous_name": "Laso'ay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kalotong": {
    "chinese_name": "加里洞部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalotong",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fata-an": {
    "chinese_name": "馬太鞍部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fata' an",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tafalong": {
    "chinese_name": "太巴塱部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tafalong",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fahol": {
    "chinese_name": "馬佛部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fahol",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-o-kakay": {
    "chinese_name": "烏卡蓋部落",
    "chinese_name_alt": [],
    "indigenous_name": "O kakay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tafugan": {
    "chinese_name": "三富橋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tafugan",
    "indigenous_name_alt": [
      "Tafogan"
    ],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette (the only confirmed-independent identity source) has 'Tafugan'. temp_dialects separately recorded 'Tafogan' for the same buluo, kept as indigenous_name_alt, but that source isn't independent (see sources.json), so this isn't treated as a genuine cross-source conflict — CIP's value stands."
  },
  "ami-tisilan": {
    "chinese_name": "靜安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tisilan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cawi": {
    "chinese_name": "靜浦部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cawi",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-laeno": {
    "chinese_name": "大港口部落",
    "chinese_name_alt": [],
    "indigenous_name": "Laeno",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-makotaay-fengbin": {
    "chinese_name": "港口部落",
    "chinese_name_alt": [],
    "indigenous_name": "Makotaay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette lists 'Makotaay' for this buluo too — the earlier suspicion that this was a copy-paste duplicate of ami-makotaay-yuli (瑪谷達璦部落, 玉里鎮) is resolved: both genuinely share the name within the same single source. Settled."
  },
  "kavalan-kodic": {
    "chinese_name": "立德部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kodic",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-malaloong": {
    "chinese_name": "東興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Malaloong",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-haciliwan": {
    "chinese_name": "八里灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Haciliwan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "kavalan-paterungan": {
    "chinese_name": "新社部落",
    "chinese_name_alt": [],
    "indigenous_name": "Paterungan",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-fakong": {
    "chinese_name": "豐濱部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fakong",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tingalaw": {
    "chinese_name": "豐富部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tingalaw",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fanaw": {
    "chinese_name": "法淖部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fanaw",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-olalip": {
    "chinese_name": "屋拉力部落",
    "chinese_name_alt": [],
    "indigenous_name": "Olalip",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ukang": {
    "chinese_name": "烏槓部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ukang",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-narowan": {
    "chinese_name": "娜魯灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Narowan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sapat": {
    "chinese_name": "掃叭頂部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sapat",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-olaw": {
    "chinese_name": "梧繞部落",
    "chinese_name_alt": [],
    "indigenous_name": "Olaw",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lacihakan": {
    "chinese_name": "拉基禾幹部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lacihakan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-koyo": {
    "chinese_name": "溫泉部落",
    "chinese_name_alt": [],
    "indigenous_name": "Koyo",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "sakizaya-maifor": {
    "chinese_name": "馬立雲部落",
    "chinese_name_alt": [],
    "indigenous_name": "Maifor",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-marorok": {
    "chinese_name": "馬聚集部落",
    "chinese_name_alt": [],
    "indigenous_name": "Marorok",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-morocan": {
    "chinese_name": "牧魯棧部落",
    "chinese_name_alt": [],
    "indigenous_name": "Morocan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-atolan": {
    "chinese_name": "阿多瀾部落",
    "chinese_name_alt": [],
    "indigenous_name": "Atolan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-langas": {
    "chinese_name": "拉加善部落",
    "chinese_name_alt": [],
    "indigenous_name": "Langas",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cirocan": {
    "chinese_name": "鶺櫓棧部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cirocan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kalala": {
    "chinese_name": "迦納納部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalala",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kiwit": {
    "chinese_name": "奇美部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kiwit",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-patawlinan": {
    "chinese_name": "巴島力安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Patawlinan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-posko": {
    "chinese_name": "璞石閣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Posko",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cilakesay": {
    "chinese_name": "吉拉格賽部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilakesay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-namisan": {
    "chinese_name": "拿彌散部落",
    "chinese_name_alt": [],
    "indigenous_name": "Namisan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-satefo": {
    "chinese_name": "下德武部落",
    "chinese_name_alt": [],
    "indigenous_name": "Satefo",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-matadim": {
    "chinese_name": "馬太林部落",
    "chinese_name_alt": [],
    "indigenous_name": "Matadim",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cinemnemay": {
    "chinese_name": "吉能能麥部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cinemnemay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lingacay": {
    "chinese_name": "苓雅仔部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lingacay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-harawan": {
    "chinese_name": "哈拉灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Harawan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ceroh": {
    "chinese_name": "春日部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ceroh",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-afih": {
    "chinese_name": "阿飛赫部落",
    "chinese_name_alt": [],
    "indigenous_name": "Afih",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tokar": {
    "chinese_name": "都旮薾部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tokar",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-angcoh": {
    "chinese_name": "安通部落",
    "chinese_name_alt": [],
    "indigenous_name": "Angcoh",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-makotaay-yuli": {
    "chinese_name": "瑪谷達璦部落",
    "chinese_name_alt": [],
    "indigenous_name": "Makotaay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette lists 'Makotaay' for this buluo too — see ami-makotaay-fengbin (港口部落, 豐濱鄉), which shares the same indigenous name. Confirmed as a real coincidence within the same single source, not a transcription error."
  },
  "ami-lohok": {
    "chinese_name": "洛合谷部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lohok",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-mangcelan": {
    "chinese_name": "滿自然部落",
    "chinese_name_alt": [],
    "indigenous_name": "Mangcelan",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-takay": {
    "chinese_name": "達蓋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Takay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-silangkong": {
    "chinese_name": "喜瑯宮部落",
    "chinese_name_alt": [],
    "indigenous_name": "Silangkong",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cihakay": {
    "chinese_name": "吉哈蓋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cihakay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sedeng": {
    "chinese_name": "瑟冷部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sedeng",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-monating": {
    "chinese_name": "姆拉丁部落",
    "chinese_name_alt": [],
    "indigenous_name": "Monating",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cirakesay": {
    "chinese_name": "基拉歌賽",
    "chinese_name_alt": [],
    "indigenous_name": "Cirakesay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cihalaay": {
    "chinese_name": "黑暗部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cihalaay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-maliwang": {
    "chinese_name": "馬里旺部落",
    "chinese_name_alt": [],
    "indigenous_name": "Maliwang",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-lupo": {
    "chinese_name": "露埔部落",
    "chinese_name_alt": [],
    "indigenous_name": "Lupo",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cilamitay": {
    "chinese_name": "吉拉米代部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilamitay",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pacuya": {
    "chinese_name": "巴族耶部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pacuya",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kalokapuk": {
    "chinese_name": "大埔部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalokapuk",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cipuwa": {
    "chinese_name": "慶豐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cipuwa",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-dihekoay": {
    "chinese_name": "陸安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Dihekoay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciataw": {
    "chinese_name": "福原部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciataw",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kawaliwali": {
    "chinese_name": "大坡部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kawaliwali",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cicalaay": {
    "chinese_name": "福文部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cicala'ay",
    "indigenous_name_alt": [],
    "dialect": [
      "恆春阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fangafangasan": {
    "chinese_name": "新興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fangafangasan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-muliyaw": {
    "chinese_name": "白毛寮部落",
    "chinese_name_alt": [
      "振興部落"
    ],
    "indigenous_name": "Moliyaw",
    "indigenous_name_alt": [
      "Muliyaw"
    ],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "verified",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）",
      "臺灣原住民族事典 (aborgpedia.alcd.center)"
    ],
    "notes": "CIP gazette confirms the current name. 2024年（113年）由「振興部落 Muliyaw」更名為「白毛寮部落 Moliyaw」（原民會公告，aborgpedia 交叉確認）；前名稱保留為 chinese_name_alt／indigenous_name_alt。"
  },
  "ami-cikowaay": {
    "chinese_name": "富興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cikowa'ay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kalahaay": {
    "chinese_name": "民豐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalahaay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciliksay": {
    "chinese_name": "麒麟部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciliksay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-mararoong": {
    "chinese_name": "美山部落",
    "chinese_name_alt": [],
    "indigenous_name": "Mararo'ong",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-madawdaw": {
    "chinese_name": "麻荖漏部落",
    "chinese_name_alt": [],
    "indigenous_name": "Madawdaw",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-piyoxo": {
    "chinese_name": "小馬部落",
    "chinese_name_alt": [],
    "indigenous_name": "Piyoxo",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-torik": {
    "chinese_name": "都歷部落",
    "chinese_name_alt": [],
    "indigenous_name": "Torik",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-dadowacen": {
    "chinese_name": "玉水橋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Dadowacen",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-tomiyac": {
    "chinese_name": "重安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tomiyac",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cirarokohay": {
    "chinese_name": "芝田部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cirarokohay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-pisirian": {
    "chinese_name": "比西里岸部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pisirian",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-folalacay": {
    "chinese_name": "小港部落",
    "chinese_name_alt": [],
    "indigenous_name": "Folalacay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-saaniwan": {
    "chinese_name": "宜灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sa'aniwan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-paongaongan": {
    "chinese_name": "八嗡嗡部落",
    "chinese_name_alt": [],
    "indigenous_name": "Paongaongan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kahciday": {
    "chinese_name": "和平部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kahciday",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-makrahay": {
    "chinese_name": "真柄部落",
    "chinese_name_alt": [],
    "indigenous_name": "Makrahay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-ciwkangan": {
    "chinese_name": "長光(石坑)部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciwkangan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-asiroay-2": {
    "chinese_name": "阿奚露艾部落",
    "chinese_name_alt": [],
    "indigenous_name": "Asiroay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-paanifong": {
    "chinese_name": "巴阿尼豐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pa'anifong",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-kalifangar": {
    "chinese_name": "佳尼發納部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalifangar",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-fafokod": {
    "chinese_name": "發富谷部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fafokod",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-howak": {
    "chinese_name": "乎哇固部落",
    "chinese_name_alt": [],
    "indigenous_name": "Howak",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-etolan": {
    "chinese_name": "阿度蘭部落",
    "chinese_name_alt": [
      "都蘭部落"
    ],
    "indigenous_name": "'Etolan",
    "indigenous_name_alt": [
      "Dulan",
      "Etolan",
      "A'tolan",
      "Atolan"
    ],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-alapawan": {
    "chinese_name": "阿拉巴灣部落",
    "chinese_name_alt": [],
    "indigenous_name": "Alapawan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-sena": {
    "chinese_name": "順那部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sena'",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-cilafinan": {
    "chinese_name": "基拉菲婻部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilafinan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-maolaway": {
    "chinese_name": "瑪屋撈外部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ma'olaway",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-dikidiki": {
    "chinese_name": "利吉部落",
    "chinese_name_alt": [],
    "indigenous_name": "Dikidiki",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-falangaw": {
    "chinese_name": "馬蘭部落",
    "chinese_name_alt": [],
    "indigenous_name": "Falangaw",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette confirms 'Falangaw'. 豐年祭 地圖/data.js (id tt-tt-01, src tt_malan_fb — a Facebook community-health-station page, not an authoritative source) previously had 'Kiluma'an', which was wrong; corrected 2026-06-30."
  },
  "pwn-kalaluran": {
    "chinese_name": "卡拉魯然部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalaluran",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-siafulungay": {
    "chinese_name": "建農部落",
    "chinese_name_alt": [],
    "indigenous_name": "Siafulungay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-asiroay": {
    "chinese_name": "阿西路愛部落",
    "chinese_name_alt": [],
    "indigenous_name": "Asiroay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "pyu-papulu": {
    "chinese_name": "巴布麓部落",
    "chinese_name_alt": [],
    "indigenous_name": "Papulu",
    "indigenous_name_alt": [],
    "dialect": [],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)"
    ],
    "notes": "Seeded from CIP 核定部落結果 gazette (data.cip.gov.tw, dataset A53000000A-112041). Not yet cross-checked against a second source."
  },
  "ami-sililasay": {
    "chinese_name": "月眉（上部落）",
    "chinese_name_alt": [],
    "indigenous_name": "Sililasay",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  "ami-siapaluway": {
    "chinese_name": "月眉（中部落）",
    "chinese_name_alt": [],
    "indigenous_name": "Siapaluway",
    "indigenous_name_alt": [],
    "dialect": [
      "南勢阿美語"
    ],
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  }
};
const BULUO_UNCOVERED = [
  {
    "id": "ami-ancoh",
    "chinese_name": "安住部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ancoh",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "county": "花蓮縣",
    "township": "富里鄉",
    "village": "吳江村",
    "lat": 23.273,
    "lng": 121.293,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-talampo",
    "chinese_name": "達蘭埠部落",
    "chinese_name_alt": [],
    "indigenous_name": "Talampo",
    "indigenous_name_alt": [],
    "dialect": [
      "秀姑巒阿美語"
    ],
    "county": "花蓮縣",
    "township": "富里鄉",
    "village": "新興村",
    "lat": 23.273,
    "lng": 121.293,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-tidaan",
    "chinese_name": "石梯坪部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tida'an",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "花蓮縣",
    "township": "豐濱鄉",
    "village": "港口村",
    "lat": 23.634,
    "lng": 121.49,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-dipit",
    "chinese_name": "復興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Dipit",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "花蓮縣",
    "township": "豐濱鄉",
    "village": "新社村",
    "lat": 23.634,
    "lng": 121.49,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-macaran",
    "chinese_name": "旭海（馬查蘭）部落",
    "chinese_name_alt": [],
    "indigenous_name": "Macaran",
    "indigenous_name_alt": [],
    "dialect": [
      "恆春阿美語"
    ],
    "county": "屏東縣",
    "township": "牡丹鄉",
    "village": "旭海村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-cilalongay",
    "chinese_name": "吉拉龍噯部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cilalongay",
    "indigenous_name_alt": [],
    "dialect": [
      "恆春阿美語"
    ],
    "county": "臺東縣",
    "township": "太麻里鄉",
    "village": "金崙村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-sasaljak",
    "chinese_name": "沙薩拉克部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sasaljak",
    "indigenous_name_alt": [],
    "dialect": [
      "恆春阿美語"
    ],
    "county": "臺東縣",
    "township": "太麻里鄉",
    "village": "香蘭村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-anasolay",
    "chinese_name": "荒野部落",
    "chinese_name_alt": [],
    "indigenous_name": "Anasolay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "太麻里鄉",
    "village": "美和村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-takidis",
    "chinese_name": "德其里部落",
    "chinese_name_alt": [],
    "indigenous_name": "Takidis",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "太麻里鄉",
    "village": "泰和村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-kalitood",
    "chinese_name": "山里部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kalito'od",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "卑南鄉",
    "village": "嘉豐村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-fudafudak",
    "chinese_name": "莿桐部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fudafudak",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "卑南鄉",
    "village": "富山村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-carapongay",
    "chinese_name": "?橋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Carapongay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "寧埔村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pasongan",
    "chinese_name": "八桑安部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pasongan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "寧埔村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-sadipongan",
    "chinese_name": "三間屋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sadipongan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "三間村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-tapowaray-saranawan",
    "chinese_name": "大俱來部落",
    "chinese_name_alt": [],
    "indigenous_name": "Tapowaray或Saranawan",
    "indigenous_name_alt": [
      "Tapowaray"
    ],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "三間村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette (the only confirmed-independent identity source) has 'Tapowaray或Saranawan'. temp_dialects separately recorded only 'Tapowaray' for the same buluo, kept as indigenous_name_alt, but that source isn't independent (see sources.json), so this isn't treated as a genuine cross-source conflict — CIP's value stands."
  },
  {
    "id": "ami-polot",
    "chinese_name": "大峰峰部落",
    "chinese_name_alt": [],
    "indigenous_name": "Polo't",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "樟原村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pakaraac",
    "chinese_name": "巴卡拉阿茲部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pakara'ac",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "竹湖村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-mornos",
    "chinese_name": "永福部落",
    "chinese_name_alt": [],
    "indigenous_name": "Mornos",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "竹湖村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-cikadaan",
    "chinese_name": "南溪阿美部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cikadaan",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "三間村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-cidatayay",
    "chinese_name": "烏石鼻部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cidatayay",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "寧埔村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-kinanoka",
    "chinese_name": "僅那鹿角部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kinanoka",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "寧埔村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-koladot",
    "chinese_name": "樟原部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kolado't",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "樟原村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-ta-man",
    "chinese_name": "膽曼部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ta?man",
    "indigenous_name_alt": [],
    "dialect": [
      "海岸阿美語"
    ],
    "county": "臺東縣",
    "township": "長濱鄉",
    "village": "寧埔村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pailasan",
    "chinese_name": "八伊拉善部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pailasan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "瑞和村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-salinliw",
    "chinese_name": "山領榴部落",
    "chinese_name_alt": [],
    "indigenous_name": "Salinliw",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "永安村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-kanaopu",
    "chinese_name": "卡拿吾部部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kanao'pu",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "瑞隆村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-rekat",
    "chinese_name": "永昌部落",
    "chinese_name_alt": [],
    "indigenous_name": "Rekat",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "永安村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-parayapay",
    "chinese_name": "和平部落",
    "chinese_name_alt": [],
    "indigenous_name": "Parayapay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "鹿野村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-efong",
    "chinese_name": "瑞源部落",
    "chinese_name_alt": [],
    "indigenous_name": "Efong",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "瑞源村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pakalaac",
    "chinese_name": "瑞興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pakala'ac",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "鹿野鄉",
    "village": "瑞和村",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pongodan",
    "chinese_name": "大橋部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pongodan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "南榮里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pakurung",
    "chinese_name": "巴古崙部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pakurung",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "新園里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pasawali",
    "chinese_name": "巴沙哇力部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pasawali",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "富岡里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-karoroan",
    "chinese_name": "加路蘭部落",
    "chinese_name_alt": [],
    "indigenous_name": "Karoroan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "富岡里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-pusong",
    "chinese_name": "布頌部落",
    "chinese_name_alt": [],
    "indigenous_name": "Pusong",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "四維里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-kakawasan",
    "chinese_name": "石山部落",
    "chinese_name_alt": [],
    "indigenous_name": "Kakawasan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "富豐里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-ining",
    "chinese_name": "伊濘部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ining",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "永樂里、豐樂里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-alapanay",
    "chinese_name": "阿拉巴奈部落",
    "chinese_name_alt": [],
    "indigenous_name": "Alapanay",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "豐里里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-matang",
    "chinese_name": "馬當部落",
    "chinese_name_alt": [],
    "indigenous_name": "Matang",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "豐谷里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-apapuro",
    "chinese_name": "高坡部落",
    "chinese_name_alt": [],
    "indigenous_name": "Apapuro",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "豐谷里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-sihodingan",
    "chinese_name": "常德部落",
    "chinese_name_alt": [],
    "indigenous_name": "Sihodingan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "豐榮里、 豐谷里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-fukid",
    "chinese_name": "新馬蘭部落",
    "chinese_name_alt": [],
    "indigenous_name": "Fukid",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "臺東市",
    "village": "南榮里",
    "lat": 22.754,
    "lng": 121.149,
    "coord_precision": "township",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": "CIP gazette confirms 'Fukid'. Briefly flagged as 'Fukia' per a maintainer correction on 2026-06-30, then self-corrected back to 'Fukid' the same day, matching the CIP gazette value — closed."
  },
  {
    "id": "ami-cu-ki-ngo",
    "chinese_name": "月眉部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cu ki ngo",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "月眉里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-cipurungan",
    "chinese_name": "隆興部落",
    "chinese_name_alt": [],
    "indigenous_name": "Cipurungan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "里?里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-parupu",
    "chinese_name": "新福部落",
    "chinese_name_alt": [],
    "indigenous_name": "Parupu",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "新福里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-himoti",
    "chinese_name": "電光部落",
    "chinese_name_alt": [],
    "indigenous_name": "Himoti",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "電光里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-takofan",
    "chinese_name": "德高部落",
    "chinese_name_alt": [],
    "indigenous_name": "Takofan",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "德高里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  },
  {
    "id": "ami-ciwcia",
    "chinese_name": "豐泉部落",
    "chinese_name_alt": [],
    "indigenous_name": "Ciwcia",
    "indigenous_name_alt": [],
    "dialect": [
      "馬蘭阿美語"
    ],
    "county": "臺東縣",
    "township": "關山鎮",
    "village": "豐泉里",
    "lat": null,
    "lng": null,
    "coord_precision": "unknown",
    "status": "single-source",
    "sources": [
      "原住民族委員會核定部落結果 (CIP gazette)",
      "暫定族語別分類來源（待補充正式引註）"
    ],
    "notes": ""
  }
];
